- name: stop playbook if any node fails
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: start service
      service:
        name: httpd
        state: started
