- name: Install a package specified by the extra_package variable
  hosts: web2
  vars:
    package_name: "{{ extra_package }}"
  tasks:
    - name: install package if htop
      package:
        name: "{{ package_name }}"
        state: present
      when: extra_package is defined and package_name  == "htop"
